### ISSUE TITLE
Socket Hang Up problem

### ISSUE THREAD

**Issue by joannesalfa** [totaljs/examples#19]
Hi, I used the example live-streaming-upload, I've followed the instruction, I ran 2 terminals, one to run node index.js and another upload.client.js but I'm ended up with this:

`Mac-mini-de-Ivan:live-streaming-upload Ivan$ node upload-client.js
[ '/Users/Ivan/Desktop/e/abstract_pyramids-1920x1080.jpg',
  '/Users/Ivan/Desktop/e/alamanos_beach-1920x1080.jpg',
  '/Users/Ivan/Desktop/e/autumn_sunlight-1920x1080.jpg',
  '/Users/Ivan/Desktop/e/bananaman-1920x1080.jpg' ]
–----> /Users/Ivan/Desktop/e/abstract_pyramids-1920x1080.jpg
ERROR { [Error: socket hang up] code: 'ECONNRESET' } Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:293:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)`

I don't know what means socket hang up.

Would you mind how to solve this problem?

**Comment by joannesalfa** [comment]
Another error isn't related to socket hang up

 `Mac-mini-de-Ivan:live-streaming-upload Ivan$ node upload-client.js
[ '/Users/Ivan/Desktop/e/abstract_pyramids-1920x1080.jpg',
  '/Users/Ivan/Desktop/e/alamanos_beach-1920x1080.jpg',
  '/Users/Ivan/Desktop/e/autumn_sunlight-1920x1080.jpg',
  '/Users/Ivan/Desktop/e/bananaman-1920x1080.jpg' ]
–----> /Users/Ivan/Desktop/e/abstract_pyramids-1920x1080.jpg
ERROR { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)`

**Comment by petersirka** [comment]
Hi @joannesalfa,
what version of total.js do you use? I removed streaming in `v1.7.1` because the maintenance is very hard. Thanks.

**Comment by joannesalfa** [comment]
Sorry for late reply. @petersirka

Well, I don't know how to check the correct version of total.js, I've used npm install from this site:
http://docs.totaljs.com/v1.7.x/en.html#pages~Getting%20started

The version says 1.7.x

**Comment by petersirka** [comment]
No problem. You have latest version of total.js and this version doesn't have streaming. What do you want to do with this streaming? Maybe I'll help you find another solution.

Thanks :-)
