### ISSUE TITLE
Email content

### ISSUE THREAD

**Issue by IReivax** [totaljs/examples#23]
Hey Peter,

How can I fill the mail content? 

(There's no doc about the arguments about the mail() function. You took the example with a redirection on a .html page.)

Thanks.

**Comment by petersirka** [comment]
Hi @IReivax,
`F.mail()` or `controller.mail()` <http://docs.totaljs.com/v1.8.x/en.html#api~FrameworkController~controller.mail>:

```javascript
function some_action() {
    var self = this;
    var message = self.mail('user@email.com', 'SUBJECT', '~view-mail-user', { name: 'Peter Širka' });
    message.bcc('my@copy.com');
}
```

1. the content of the e-mail is `/views/view-mail-user.html` (but important: turn off a layout)
2. a rendered view will be sent as email body

EXAMPLE: <https://github.com/totaljs/examples/tree/master/controller-mail>

Or did you mean something else?
Thanks.

**Comment by IReivax** [comment]
+1 (but important: turn off a layout)

Thanks, it solved.
