### ISSUE TITLE
Websocket handshake never completes

### ISSUE THREAD

**Issue by darrudi** [totaljs/examples#24]
Hi Peter,
I have this weird problem with websocekts:

WHAT WORKS:
The client websocket connects to the server as expected. The server receives the websocket connection request successfully and establishes the connection. Then the client and server start communicating smoothly and with no problem.

WHAT DOES NOT WORK:
However it seems that `total.js` never sends the final ACK for the browser's upgrade request so that the browser (tested on Chrome and Firefox) keeps the connection in `pending` state and thinks the connection request has timed out and closes the connection after a while. The connection times out after 2 minutes on Chrome. So the websocket connection only lasts for two minutes and closes unexpectedly.

HOW TO REPRODUCE:
1- download the `angularjs-websocket` example from the tota.js's examples repo,
2- modify/add the following lines at the end of `default.js` controller:
```
self.on('close', function(client) {
	console.log(new Date() + ': SERVER: onclose');
	refresh();
});

self.on('open', function(client) {
	console.log(new Date() + ': SERVER: onopen');
});
```
3- run the project. Please pay attention to the `pending` state on dev tool's network tab:
![002](https://cloud.githubusercontent.com/assets/5983954/8324723/7d74ba76-1a68-11e5-90a7-f257884fe95f.png)

4- this is what you'll see after 2 minutes:
![001](https://cloud.githubusercontent.com/assets/5983954/8324695/3d8721c4-1a68-11e5-95f0-856b9b4001c6.png)

**Comment by petersirka** [comment]
I'll test it today and I'll give you a feedback.
Thanks for the report.

**Comment by petersirka** [comment]
Try to download latest version of total.js from GitHub or `npm install total.js@beta`. My chrome

### Auto-close testing (no problem)

__Chrome (closed manually)__:
![manual](https://cloud.githubusercontent.com/assets/2414252/8325165/7b5e0596-1a57-11e5-817d-e40bfaa67026.png)

__Firefox (closed manually)__:
![firefox](https://cloud.githubusercontent.com/assets/2414252/8325308/acda29e6-1a58-11e5-9aef-8d3b6df2f4c4.png)

Try auto-close here: <https://www.websocket.org/echo.html> and <https://www.privater.eu>

### Websocket "pending" test (no problem, same like another)

__Gitter.com__

![gitter](https://cloud.githubusercontent.com/assets/2414252/8325177/8d717e98-1a57-11e5-84cc-dd20ecedcd8f.png)

__Websocket.com echo test__

![websocket-echo](https://cloud.githubusercontent.com/assets/2414252/8325182/94913754-1a57-11e5-8611-e9b9106598e7.png)

---

I will waiting. Thanks.

**Comment by darrudi** [comment]
I installed the newest version:
```
$ npm install total.js@beta
total.js@1.8.1-42 node_modules\total.js
```
and it works!
Anyway I am sure the version `1.8.0` suffers from this problem.
Thanx for your quick reply Peter,

**Comment by petersirka** [comment]
Hmmm, it's really interesting.
I'll look for changes between versions.

Thanks.
