### ISSUE TITLE
Cross domain access

### ISSUE THREAD

**Issue by sarankup** [totaljs/examples#25]
Hi, I am running my java application under localhost:8080, where in I GET request via ajax, whereas to total.js server running under localhost:8000
```
$.ajax({
type:"GET",data:'lid='+gprofile.lid,crossDomain:true,dataType:"jsonp",
url:"http://localhost:8000/getmyname",
success:function(data){
console.log(data);
}
});//ajax
```
And the console throws error as below
```
GET http://localhost:8000/getmyname?callback=jQuery21309127184972167015_1435457894103&lid=5584b74914b7fe30217c8321&_=1435457894104 
```

controller.js is set as 
```
framework.route('/getmyname',getmyname,['post']);
```

Please advise how to set my server to access cross-domain access or any other,

**Comment by petersirka** [comment]
Hi @sarankup,
can you send me your whole example on my e-mail? I must test it.

Thanks.

**Comment by matusszabo** [comment]
Hi @sarankup,
you are using JSONP (dataType:"jsonp") in your AJAX call. That means you are not making POST, but GET request, and in your controller is flag POST - framework.route('/getmyname',getmyname,['post']). Try it with empty flags array framework.route('/getmyname',getmyname,[]).

**Comment by sarankup** [comment]
Thanks Both,

I have change the framework as mentioned by Matusszabo. Now, I received the content from the server. How to write controller function to JSONP response. I found one solution from the below web link.

https://groups.google.com/forum/#!msg/totaljs/qUV8h2Qilkw/dfXMeqyGd5YJ

But, I am not sure what does it mean "self.req.data.get.callback"

Please help.

**Comment by sarankup** [comment]
Thanks. This is fixed according to  framework.route('/getmyname',getmyname,[]).

Is this the write way to send jsonp
```
self.content('myfun('+JSON.stringify(docs.land)+');');
```

**Comment by petersirka** [comment]
Hi @sarankup,
new beta version supports JSONP `npm install total.js@beta`.
<https://github.com/totaljs/framework/blob/v1.8.1/changes.txt#L29>

Thanks.
