### ISSUE TITLE
HTTP GET Security 

### ISSUE THREAD

**Issue by sarankup** [totaljs/examples#26]
Hi,

This is the common challenge, but looking for your advise. I have a web application which is running under total.js where my database lives. I have my mobile app which is read/delete/modify my total.js web server using AJAX call. (The same can be done using web application itself, where I manage all session variable.)

I do not want the mobile app user to sign-in all the time but at the first time. At the first login, I store the user ID in the localstorage and rest of the AJAX accesses I use localstorage details as credentials. In this case I will not have session variable. How I can restrict the total.js application such total.js will response only for my mobile app HTTP GET request, not by others.

**Comment by matusszabo** [comment]
Hi,
Just store your rest API key in users collection in the database, or somewhere you decide. Then use famework.onAuthorization = function(req, res, flags, next) { ... } to implement your custom auth process - read from db/cache and callback user object next(true, user); or next(false) if the user is not found.
