### ISSUE TITLE
session cluster redis

### ISSUE THREAD

**Issue by alex986** [totaljs/examples#28]
Hi, I use the example session cluster redis, when I run the app in the console appear this: 
** OBSOLETE module.session: exports.install = function(framework <-- REMOVE ARGUMENT, options, name) { ...
** ReferenceError: delegate_request is not defined ReferenceError: delegate_request is not defined

How to solve this problem?

**Comment by petersirka** [comment]
Hi @alex986,
I have fixed this problem.

Thanks.

**Comment by alex986** [comment]
Thanks, but now appear this:

ReferenceError: delegate_request is not defined ReferenceError: delegate_request is not defined.

**Comment by petersirka** [comment]
I have found `delegate_request` in the uninstall statement.
Try it again.

Sorry.

**Comment by alex986** [comment]
Thanks I reinstall total.js and works fine. The problem is when I download a "empty-project with the framework".
