### ISSUE TITLE
@section only works if I use single quotes

### ISSUE THREAD

**Issue by vehuel** [totaljs/examples#29]
If I create a section like this: @{section("scriptsFooter")}

using double quotes, the view can't find the section.

Thank you for this great framework.

**Comment by petersirka** [comment]
Hi @vehuel,
can you create a small example with this problem? Please send me it (.zip) on my email <petersirka@gmail.com>. 

Thank youo for your compliment :+1:

**Comment by vehuel** [comment]
Here it is.

https://dl.dropboxusercontent.com/u/17271732/views-place-sections.zip

I changed the line **@{section('header')}** to **@{section("header")}** and the "SECTION: header" div doesn't show anymore.

The total.js does not added the 2 scripts (jquery and angular) automatically too.

Screenshot from what I get.
![screenshot](https://cloud.githubusercontent.com/assets/841199/9887319/f78e753c-5bbc-11e5-9854-f3de7148375c.PNG)


Thank you.

**Comment by petersirka** [comment]
Yes, you right. I have fixed it now.
Please try it `npm install total.js@beta`.

Many thanks!
