### ISSUE TITLE
Sending mail using gmail fails

### ISSUE THREAD

**Issue by molda** [totaljs/examples#31]
I've just tried mail example and it failed.
Google says that the app that is trying to connect is "less secure" and the only way around is to allow "Access for less secure apps" which i have currently disabled.

https://www.google.com/settings/security/lesssecureapps

More info: https://support.google.com/mail/answer/78754

I'm running my app on localhost

[Error: 534 5.7.14  HTTPS://SUPPORT.GOOGLE.COM/MAIL/ANSWER/78754 FU5SM404200WIC.0 - GSMTP]
======= 2015-09-15 20:25:38: Error: 534 5.7.14  HTTPS://SUPPORT.GOOGLE.COM/MAIL/ANSWER/78754 FU5SM404200WIC.0 - GSMTP Error: 534 5.7.14  HTTPS://SUPPORT.GOOGLE.COM/MAIL/ANSWER/78754 FU5SM404200WIC.0 - GSMTP
    at TLSSocket.<anonymous> (D:\blabla\api\node_modules\total.js\mail.js:685:11)
    at TLSSocket.emit (events.js:107:17)
    at TLSSocket.<anonymous> (D:\blabla\api\node_modules\total.js\mail.js:566:12)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

Is there something wrong on my end or can i do something to make the app "more secure"?

Thanks for any help

**Comment by matusszabo** [comment]
Hi @molda,
gmail has 2-step verification: https://www.google.com/landing/2step/#tab=how-it-works 
You need to set it for your account: "You see the page only if you are not using Google Apps or have enabled two-factor authentication for the account." Let me know if it help.

thank you

**Comment by molda** [comment]
Hi @matusszabo 
cool, it works, i also had to create "app password" for my app and use it instead of my own password which i didn't realize first.
Thank You very much
