### ISSUE TITLE
Content-type in plain

### ISSUE THREAD

**Issue by maxxam11** [totaljs/examples#32]
Hello.

I send plain in controller with headers:

`
self.plain('* {color: red;}', 'Content-type: text/css');
`

but my response headers in browser:

`
Content-Type:text/plain; charset=utf-8
`

**Comment by matusszabo** [comment]
Hi @maxxam11,
as documentation says, second argument should be an object: http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkController~controller.plain

**Comment by maxxam11** [comment]
Ok. I understood.
I need to generate dinamic css file, how i can do it?

--
С уважением, Максим Карачев
11 нояб. 2015 г. 18:52 пользователь "Matus Szabo" <notifications@github.com>
написал:

**Comment by matusszabo** [comment]
Try controller.content(body, type, [headers]);  http://docs.totaljs.com/v1.9.x/en.html#api~FrameworkController~controller.content

**Comment by petersirka** [comment]
Thanks @matusszabo.

**Comment by maxxam11** [comment]
Thank you, this is that i need.

--
С уважением, Максим Карачев
11 нояб. 2015 г. 19:10 пользователь "Peter Širka" <notifications@github.com>
написал:

**Comment by matusszabo** [comment]
@maxxam11 You are welcome, @petersirka :)
