### ISSUE TITLE
Ionic framework

### ISSUE THREAD

**Issue by ram-you** [totaljs/examples#33]
Hi,
Can someone provide example with ionic framework.
Thank you.

**Comment by petersirka** [comment]
HI @ram-you,
`ionic` is client-side framework and your don't need total.js for it.

<http://ionicframework.com/getting-started/>

**Comment by ram-you** [comment]
Hi @petersirka , thank you for quick response.
Angular is also client-side framework. However an example is provided.
I'm very NEW to Total.js. I thought that thanks to Isomorphic code we can render server side.

**Comment by petersirka** [comment]
No problem. Ionic as website:
<https://forum.ionicframework.com/t/deploy-ionic-app-as-a-website/2845>

Thanks.

**Comment by ram-you** [comment]
Thanks.
