### ISSUE TITLE
For v2 release, it would be nice if live demos were available

### ISSUE THREAD

**Issue by aubergine10** [totaljs/examples#41]
For many of the examples, it would be nice if there was a live online demo showing the results so developers could see the results without having to download the example. They could have the code open in one window and the live demo open in another window and see the two side by side.

For example, in the `bootstrap` example, the `readme.md` could include a link to `http://examples.totaljs.com/bootstrap/` so the developer can see what the end result looks like in the browser.

The `blocks` example is another one where a demo would be useful, as the developer could see how switching between endpoints changes the includes and also look at the resulting `admin.js` and `admin.css` files. The live demo would be at `http://examples.totaljs.com/blocks/`.

To implement live previews I assume it would require the routes in each example to be unique, or maybe there is some other way? If you think such an approach would be useful, let me know what sort of changes are required and I'll start tweaking the examples to facilitate running them side by side on the same node server.

We'd probably need some way to tweak the examples when running on the demo server - for example, you wouldn't want loads of emails from the `controller-mail` example, so we'd need some way to prevent it sending mails when running on demo server. Perhaps running the demo site in 'debug' mode would facilitate functionality switching?

**Comment by petersirka** [comment]
@aubergine10 good idea and I will think about it.
