### ISSUE TITLE
authorization-www-basic - should this example be removed?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/examples#43]
This example seems somewhat pointless...

https://github.com/totaljs/examples/tree/master/authorization-www-basic

In particular, what is `self.baa` supposed to be?

Would it be best to just remove this example and instead have people go to the main 'auth' module?

Alternatively, the example could be refactored to show how to route depending on `'authrorized'` vs `'unauthorized'`, thus providing a very basic example of how `F.onAuthorize` delegate and associated flags work?

**Comment by petersirka** [comment]
@aubergine10 the example shows __Basic access authentication__ nicely. It's very important for some projects. We can update readme about `F.onAuthorize`, but the example is important.

Thanks.

**Comment by aubergine10** [comment]
I still don't understand what the `self.baa` is about because the example code doesn't give an indication as to where `.baa` is being defined or any context/examples about the situation in which the basic authorisation would be used.

**Comment by aubergine10** [comment]
I finally found out what `.baa` is!

https://github.com/totaljs/framework/blob/v2.0.0/index.js#L12671

https://en.wikipedia.org/wiki/Basic_access_authentication

Will add this to the readme.md for the example later today.

**Comment by aubergine10** [comment]
Looking at the code, `.baa()` doesn't seem to do any checks for credentials in the URL?

```
https://user:password@www.example.com/
```

Is there a recommended way to get that information?

**Comment by petersirka** [comment]
@aubergine10 `controller.baa()` reads only request headers. For URL auth use `controller.uri.auth` or `req.uri.auth`.

Thanks!
