### ISSUE TITLE
What is difference between `@` and `!` in flags?

### ISSUE THREAD

**Issue by aubergine10** [totaljs/examples#45]
The [auth module](https://github.com/totaljs/modules/tree/master/Security/auth#how-to-use-roles) suggests using **`!role`** whereas the [authorization-roles example](https://github.com/totaljs/examples/blob/master/authorization-roles/definitions/authorization.js) uses **`@role`**. Is there a difference?

**Comment by petersirka** [comment]
My mistake, but `!` and `@` are skipped in comparing flags.

**Comment by petersirka** [comment]
So it doesn't matter (I hope).

**Comment by aubergine10** [comment]
The `@role` is nicer to work with. The `!role` makes it read like `not role`.

**Comment by aubergine10** [comment]
Hrm, if `@` flags were skipped, the [authorization-roles example](https://github.com/totaljs/examples/blob/master/authorization-roles/definitions/authorization.js) wouldn't work. So maybe it's only the `!` flags that are ignored?

**Comment by petersirka** [comment]
I had to remove `!role`, so now `@role` will be work.
There was a bug. Many thanks!
