### ISSUE TITLE
CSRF example link is down

### ISSUE THREAD

**Issue by truedat101** [totaljs/examples#46]
https://github.com/petersirka/total.js/tree/master/examples/contact-form

shoudl be:

https://github.com/totaljs/examples/tree/master/contact-form

**Comment by aubergine10** [comment]
Which page is the wrong link on?

**Comment by truedat101** [comment]
Shovel that.  https://github.com/totaljs/examples/tree/v1.7.0/csrf  .  I just realized it's an old example, so no need to fix anything.
