### ISSUE TITLE
FrameworkView methods with angularjs

### ISSUE THREAD

**Issue by arcoirislabs** [totaljs/examples#47]
Hi,
We wanted to know how to use FrameworkView methods in templates loaded by angularjs??
Is it possible??

Thanks

**Comment by petersirka** [comment]
Hi @arcoirislabs,
is it possible when the template is generated by view engine, e.g. like this:

```javascript
exports.install = function() {
   F.route('/template/{name}/', template);
};

function template(name) {
    this.view('templates/` + name);
}
```

**Comment by arcoirislabs** [comment]
Alright. Thank you.
