### ISSUE TITLE
how to find all records with nosql in model and call in controller send to view ?

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/examples#49]
sorry about this question, i'm new in total.js.
But i find in examples and nothing like that.
please help ?

ps: good if we have super simple demo code about model, controller, view on README or website

**Comment by petersirka** [comment]
Hi, I have created a new small example:
https://github.com/totaljs/examples/tree/master/models-nosql

Thank you!

**Comment by lyquocnam** [comment]
thanks @petersirka  awesome !
