### ISSUE TITLE
[nosql]binary db file given a wrong name when update

### ISSUE THREAD

**Issue by yexing** [totaljs/examples#50]
nosql.js line 2340

    var stream = Fs.createWriteStream(framework_utils.join(self.directory, id + EXTENSION_BINARY));
should be

    var stream = Fs.createWriteStream(framework_utils.join(self.directory, self.db.name + '#' + id + EXTENSION_BINARY));

**Comment by petersirka** [comment]
Hi @yexing,
which version of Total.js do you use?

<https://github.com/totaljs/framework/blob/master/nosql.js#L2339>
Thank you!

**Comment by yexing** [comment]
v4.1.0

I've update to 5.0.1.

**Comment by petersirka** [comment]
Please send me on my email petersirka(AT)gmail(DOT)com a small example with `node_modules.
Thank you!

**Comment by yexing** [comment]
Sorry, I didn't get myself across. I've updated to 5.0.1 and the bug already fixed.

**Comment by petersirka** [comment]
Great!
