### ISSUE TITLE
Test Example

### ISSUE THREAD

**Issue by NMonst4** [totaljs/examples#51]
Hi, 

i play around with some tests and i struggle with error handling in this example. I wrap all asserts in try catch blocks to get a better error handling. Without try catch my tests run into an endless loop with no response.

```javascript
exports.run = function() {
        try{
	    F.assert('controller.increment()', function(next, name) {
                 testerror
		 assert.ok(F.controller('default').functions.increment(1) === 2, name);
		 next();
	   });
        catch(e){console.error(e);}
};
```

**Comment by NMonst4** [comment]
And is there a way to call GETSCHEMA("Modelname").workflow("test", null, "teststring"); in Tests or any other way to Test Schema functions without authentication against my app?

**Comment by petersirka** [comment]
Hi @NMonst4,
this is not good way how to handle it. Callback can't handle unexpected errors. Maybe better solution is to wrap the whole content in callback like this:

```javascript
exports.run = function() {
    F.assert('controller.increment()', function(next, name) {
        try {
            testerror
            assert.ok(F.controller('default').functions.increment(1) === 2, name);
        } catch (e) {
            console.log(e);
        }
        next();
   });
};
```

__Can you use schema again?__
Of course.

**Comment by NMonst4** [comment]
Thank you Peter for you fast response :) now everything ist working
