### ISSUE TITLE
Graphql Server with total.js

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/examples#52]
Hi author, i think this can be perfect, but i dont know how to do now.
You could have simple example about Apollo server with totaljs ?

**Comment by petersirka** [comment]
I'll look into it today.

**Comment by SatadruBhattacharjee** [comment]
Hi @petersirka , any update on GraphQL ? Thanks in advance

**Comment by Danjavia** [comment]
Some advance with graphQL using total.js?

**Comment by petersirka** [comment]
I need some GraphSQL schemas and example for creating of request. I looked into it some time ago.

**Comment by molda** [comment]
Hi  guys, i've just added simple GraphQL example https://github.com/totaljs/examples/tree/master/graphql

There's many more ways GraphQL can be used.
If you have any questions don't hesitate to ask me.
