### ISSUE TITLE
Walkthrough kind of tutorials

### ISSUE THREAD

**Issue by SatadruBhattacharjee** [totaljs/examples#56]
total.js is great.
Can you please create a meteor walkthrough kind of tutorials (https://www.meteor.com/tutorials). Currently, one confusion I am facing is that how to structure the codebase and what code part will go into which section, say I am writing a functionality , does it go to module or  definition or packages .

Thanks

**Comment by molda** [comment]
@SatadruBhattacharjee i agree that​ the Meteor tutorials is really cool, but I'm afraid we are currently too busy to create such tutorial. A lot about structure is explained in documentation https://docs.totaljs.com/latest/en.html#pages~Directory%20structure have a look and if you still not sure don't hesitate to ask at https://messenger.totaljs.com
