### ISSUE TITLE
Can't set dynamic from/replyTo

### ISSUE THREAD

**Issue by trsh** [totaljs/examples#62]
> CHANGELOG: we have replaced [replyTo] argument for [language] argument.

Why?

**Comment by molda** [comment]
Since controller.mail returns instance of MailMessage https://docs.totaljs.com/latest/en.html#api~FrameworkMail
You can do following:
```javascript
var message = controller.mail(...);
message.to(...);
message.reply(...);
```
It's all in the docs https://docs.totaljs.com

**Comment by trsh** [comment]
@molda but the function executes sending it self. So the parametrs will be set after sending happened? Or sending is done after controller function is done?

**Comment by petersirka** [comment]
Hi @trsh,
email is sent in the next `tick`. For understanding:

```javascript
var message = controller.mail(...);

// This hidden code will be executed in the next tick
setImmediate(function() {
   message.send();
});

// Your code:
message.to('...');
message.replay('...');
```

Why __language__?
Because framework can localize subject and body automatically and this change was the only way how to do it.

```javascript
var msg = controller.mail('petersirka@gmail.com', '@(This subject will be localized with the view automatically)', 'view_name', model, model.language || '');
msg.reply('your@email.com');
```

Thank you!

**Comment by trsh** [comment]
@petersirka cool. Thanks for explanation ;)
