### ISSUE TITLE
[Nuxt-Middleware] Error "hot-update" when change .vue file.

### ISSUE THREAD

**Issue by lyquocnam** [totaljs/examples#63]
<img width="505" alt="screen shot 2017-06-30 at 10 25 42 pm" src="https://user-images.githubusercontent.com/8347826/27742517-3d55be5c-5de3-11e7-9e03-0b80c35e30cc.png">

@ckpiggy please help !

**Comment by ckpiggy** [comment]
It is weird that we got the error and the page still reload properly when we are in dev.
I don't know how to solve it now. 
And you maybe have to press the "refresh" button on the browser when the hot reload not work properly.

**Comment by petersirka** [comment]
I can't answer because I don't use Nuxt.

**Comment by hilkbahar** [comment]
I have a same problem. Solve please!
