### ISSUE TITLE
I can't run ANY of the examples ... ?

### ISSUE THREAD

**Issue by blaasvaer** [totaljs/examples#66]
When I cd into an example directory and type node index.js, I get:

Error: Cannot find module 'total.js/debug'

Example:
Directory: example/workers

Running: node index.js

Result:
Error: Cannot find module 'total.js/debug'

Where do I get the debug from?

**Comment by petersirka** [comment]
@blaasvaer just install `$ npm install total.js` 👍

**Comment by blaasvaer** [comment]
Yeah, figured that out after starring at the screen for like 30 seconds : ). Stupid me ... Thanks.

**Comment by petersirka** [comment]
No problem!
