### ISSUE TITLE
Roles in authorization

### ISSUE THREAD

**Issue by g666nz** [totaljs/examples#69]
Hi peter,
I wanted a little more clarity on how to implement roles for authorization. Do you have any other examples i could go through. 

authorization.js

F.on('module#auth', function(type, name) {
	var auth = MODULE('auth');
	// "id" from auth.login()
	auth.onAuthorize = function(id, callback, flags) {
		DATABASE(function(err, connection){
			if(err != null) {
				console.log(err);
				return;
			}
			connection.query('USE system_curry', function(err, rows) {
				if (err != null) {
					console.log(err);
					return;
				}
				connection.query('SELECT * from users', function(err, rows) {
					connection.release();
					if (err != null) {
						console.log(err);
						return;
					}
					for(var i = 0; i < rows.length; i++){
					  if(rows[i].token === null ){
						callback(null);
						return;		
					  }else if(rows[i].token == id){
						callback(rows[i]);  
					  }
					}
				});
			});
		});
	};
});

controller/default.js:

The way i login

auth.login(self, rows[i].token, rows[i]);

**Comment by webdesus** [comment]
Hi @g666nz are you read [this](https://github.com/totaljs/modules/tree/master/Security/auth#how-to-use-roles)?

**Comment by g666nz** [comment]
Found it earlier, sorry i didn't update.
