### ISSUE TITLE
Compile .scss freeze

### ISSUE THREAD

**Issue by fgnm** [totaljs/examples#78]
I'm trying to include that example in my project to compile .scss files: https://github.com/totaljs/examples/tree/master/external-compile-sass.

The code works fine most of the time, but sometimes it freeze and the server does not respond when .scss is requested.
This behaviour happens after visiting 20 pages, exactly the number of max parameter in the function F.exists.

There is something wrong with temp files and the queue list.. I hope that someone could help me to understand how this example works in order to fix the bug.

**Comment by petersirka** [comment]
Hi @fgnm, thank you. I have fixed it. Only in `release` mode was the file stored in HDD and `F.exists()` expects a file in its scope. Current it works correctly. Thank you again!

**Comment by fgnm** [comment]
@petersirka Thank you too! I've just one question, why you have used `Fs.writeFileSync(tmp, content);`? Should not be better:
```JavaScript
Fs.writeFile(tmp, content, function(err) {
	if(err) {
		return res.throw500();
	}
	res.content(200, content, 'text/css', true);
});
```

In the same way, why also `sass.renderSync` is in synchronous mode?

**Comment by petersirka** [comment]
In `RELEASE` mode --> it is useless because `F.exists()` evaluates `scope` function only onetime... Therefore I have used `F.writeFileSync()`.

**Comment by fgnm** [comment]
Hi @petersirka I recently start using v4 to build a new website, I'm trying to update this example but I've got some troubles (mainly because routing files changed in v4), can you give me an help?

Thanks :)

**Comment by petersirka** [comment]
Can you send me some empty project with all troubles? I'll debug/modify it

**Comment by fgnm** [comment]
Many thanks!
This is an empty project, basically I'd like to use bootstrap from npm and allow easy customization of the scss rules, I'm stuck at `F.routeStyle` and `F.file` which I don't find a translation in v4.
[emptyproject.zip](https://github.com/totaljs/examples/files/6704788/emptyproject.zip)

**Comment by petersirka** [comment]
__Updated definition__:

```js
var sass = require('node-sass');

DEF.helpers.scss = function (name) {
	return '<link type="text/css" rel="stylesheet" href="' + F.public_css(name).replace(/\.css$/, '') + '" />';
};

function handlescss(next, tmp, req, res) {
	var filename = PATH.public(req.url);
	PATH.fs.readFile(filename, function (err, data) {
		if (err) {
			next();
			res.throw404();
		} else {
			var content = DEF.onCompileStyle(filename, data.toString('utf8'));
			if (RELEASE)
				PATH.fs.writeFile(tmp, content, () => res.content(200, content, 'text/css', true));
			else
				res.content(200, content, 'text/css', true);
		}
	});
}

ROUTE('FILE /css/*.scss', req => req.filecache(handlescss));

DEF.onCompileStyle = function (filename, content) {
	return sass.renderSync({ file: filename, data: content, outputStyle: 'compressed' }).css.toString('utf8');
};
```

**Comment by fgnm** [comment]
Always many thanks for your help, it worked flawlessly
