### ISSUE TITLE
the export of functions in business logic does not work

### ISSUE THREAD

**Issue by dispbd** [totaljs/examples#79]
Hello, dear community.

Tell me, please, why the export of functions in business logic does not work?
https://i.vgy.me/1tTcP3.png

At first I thought that the problem was in the described functions, but I did it as in the example from the github, and it still does not work.
The strange thing is that the example itself as a separate project works fine.

**Comment by petersirka** [comment]
Hi. I think you're in the wrong place because this repostiory is about Total.js framework (Node.js framework written in pure JavaScript). Your image describes something else...

**Comment by dispbd** [comment]
Sorry, I copied the wrong link, here is the correct screenshot
https://i.vgy.me/XVi2PY.png

**Comment by petersirka** [comment]
Are you sure that the error is the only one error? Or does the console contain more errors?

**Comment by molda** [comment]
You have a typo in the source directory name. 

You have sourse with **s**, but it should be source with **c**

**Comment by dispbd** [comment]
damn it...))
that's what it means to recycle all night ...

Thank you very much!!!
